#!/bin/bash
#$ -S /bin/bash
#$ -cwd

#  This requires that o
# new_species.pl --species=Jinfusca3
# and
# etraining --species=Jinfusca3 
# is done prior to the execution

unset LANG
export LD_LIBRARY_PATH=/usr/local/lib64:$LD_LIBRARY_PATH

augustus --species=Jinfusca3 --extrinsicCfgFile=extrinsic.cfg --alternatives-from-evidence=true --hintsfile=intron_hints.gff --allow_hinted_splicesites=atac --introns=on --genemodel=complete Jin03.masked.fa > aug1.out
