#!/bin/bash
#$ -S /bin/bash
#$ -cwd
#$ -pe def_slot 4-20
##$ -t 1:10

source $HOME/.bashrc
unset LANG
export LD_LIBRARY_PATH=$HOME/lcl/lib64:$HOME/lcl/lib:$LD_LIBRARY_PATH
PATH=$HOME/lcl/opt/augustus/augustus-3.0.2/bin:$HOME/lcl/bin/tophat/:$HOME/lcl/bin:$PATH
#idx=`head -n $SGE_TASK_ID RNA-seq-list | tail -1 | awk '{print $1;}'`
tbams=`sed -e 's/^/Sample_idx/' -e 's#\t.*#_thm/accepted_hits.noN.bam#' RNA-seq-list`
#tophat2 -p 4 genome_database rnaseq.fastq
date
#tophat -p $NSLOTS -o Sample_idx${idx}_thm Jin03_m_db Sample_idx$idx.aug.fq.gz
# done 

#samtools merge both.bam bowtie.global.h.bam output_directory/accepted_hits.noN.bam
samtools merge Jin03RNAs.noN.bam $tbams
samtools sort Jin03RNAs.noN.bam Jin03RNAs.noN.s
samtools index Jin03RNAs.noN.s.bam

#samtools sort -n output_directory/accepted_hits.bam output_directory/accepted_hits.s
# filter alignments with filterBam
#filterBam --uniq --paired --in output_directory/accepted_hits.s.bam --out output_directory/accepted_hits.sf.bam
#samtools sort -n Sample_idx${idx}_thm/accepted_hits.bam Sample_idx${idx}_thm/accepted_hits.s
#filterBam --uniq --paired --in Sample_idx${idx}_thm/accepted_hits.s.bam --out Sample_idx${idx}_thm/accepted_hits.sf.bam

date
